FROM python:3.10-slim AS dagit

RUN mkdir -p /app /workspace

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6

COPY requirements.txt /
RUN pip install -r /requirements.txt

COPY workspace.yaml /workspace/workspace.yaml

ENV DAGSTER_HOME=/app
ADD . ${DAGSTER_HOME}
RUN pip install -e ${DAGSTER_HOME}

WORKDIR /workspace
CMD ["dagster-webserver", "-h", "0.0.0.0", "-p", "4000", "-w", "/workspace/workspace.yaml"]
