name: DB

on:
  push:
    paths:
      - "db/**"

jobs:
  test_db:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./db

    steps:
      - uses: actions/checkout@v4

      - name: Test DB
        run: ./run-tests.sh postgres:postgres@localhost:5432
